services:

  gotenbergAPI:
    image: gotenberg/gotenberg
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://gotenbergAPI:3000/health"]

  docusaurus311:
    build: ../
    ports:
        - 3000:3000
    volumes:
      - ../PDFoutput:/app/PDFoutput
    working_dir: /app/PDF
    healthcheck:
      test: curl --fail http://docusaurus311:3000 || exit 1
      interval: 10s
      retries: 20
      start_period: 140s
      timeout: 5s
    entrypoint: >
      /bin/bash -c "
      cd /app/website &&
      npm install -g docusaurus-prince-pdf@1.2.1 &&
      yarn install &&
      yarn build &&
      yarn serve -p 3000 -h 0.0.0.0 &&
      tail -f /dev/null
      "

